# Generated by Codex on 2026-01-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
