# Generated by Django 4.2.16 on 2026-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
    ]
