# Generated by Django 4.2.16 on 2026-02-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], db_index=True, default='New', max_length=20),
        ),
    ]
