// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpdgwwhnapzchnvtvjqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZGd3d2huYXB6Y2hudnR2anF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMjEwOTcsImV4cCI6MjA1MTY5NzA5N30.XRfZAD7AZBXEFs0xuwnvp1toqER25VMFHSE26bxYlhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);